### ISSUE TITLE
Bug: RuntimeError: Read batched records out of order

### ISSUE THREAD

**Issue by mounte** [reductstore/reduct-py#79]
### What happened?

I think this is on the client side with the new handling of batched records.

Previously I did something similar to this for cloning data from one bucket to another (very similiar to the cli tool I guess)
```python
async for record in bucket_src.query(entry.name, start=t0_us, stop=t1_us):
                    try:
                        await bucket_dst.write(
                            entry.name,
                            data=record.read(1024 * 512),
                            content_length=record.size,
                            timestamp=record.timestamp,
                            content_type=record.content_type,
                            labels=record.labels,
                        )
```
I get some random crashes looking like:
RuntimeError: Read batched records out of order: 5057 != 5117
RuntimeError: Read batched records out of order: 1633 != 1853

where the offsets/indexes show random numbers...

I thought this may have something to do with the async nature of things so I rewrote it to:
```python
                async for record in bucket_src.query(entry.name, start=t0_us, stop=t1_us):
                    try:
                        d = await record.read_all()
                        await bucket_dst.write(
                            entry.name,
                            data=d,
                            content_length=record.size,
                            timestamp=record.timestamp,
                            content_type=record.content_type,
                            labels=record.labels,
                        )
```

where I await the record.read_all() early and then put that in the request to write in the destination bucket.
After that minor change things are working without a problem.

python client lib running on windows, reductstore server running on linux.

### Version

1.5 55d5787f5e7a385f0cefbcc5e481d08af8ef3ff3, Server v1.5.0-dev 202d1d58193e5ff90399bb1737f00cf182ca6800

### OS

Linux

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by atimin** [comment]
Thanks, for the report! The reason for such behaviour is that we can't read batched records in a random order.  We receive a body as a steam, and each record consumes its own part one after another one. The SDK sends the exception, then the order has been broken. 
Looks like this part works in a random order:
```python
                       await bucket_dst.write(
                            entry.name,
                            data=record.read(1024 * 512),
                            content_length=record.size,
                            timestamp=record.timestamp,
                            content_type=record.content_type,
                            labels=record.labels,
                        )
```
This is not what I expected, let me think a bit. Maybe I could hold the reading of random records inside the SDK.

**Comment by atimin** [comment]
Hey @mounte, I've found a solution. In the `main` branch, you can find the fixed `query` function, where I read all the batched records in the right order except for the last one. I've designed ReductStore to handle records of unlimited size, so a record can be a terabyte, but a batched response has a limit of 8Mb body + last record, so a big record is always the last one and can't be read in chunks in the client code.
