### ISSUE TITLE
Feature: Add custom headers to the client

### ISSUE THREAD

**Issue by mounte** [reductstore/reduct-py#80]
### Current problem

If reductstore is hsoted behind some LB/Proxy/what-not/tunnel that has additional authentication the current implementation falls short since the only headers the HttpClient provide are the bearer authorization for reductstore itself.

As an example if I use cloudflare tunnel I am provided headers like
```
CF-Access-Client-Id: some-id.access
CF-Access-Client-Secret: some-secret
```
and I would have to pass these with my requests for everything to work.

Provided the possible solution below, question remains is this a sound suggestion? Is the provided solution good enough and general enough to be of any value? 
If you think things look good I can wrap up a PR on this later this week.

### Possible solution

In http.py HttpClient __init__ add an optional parameter `extra_headers` as a dict str -> str.
Extend the self._headers with that optional extra headers if provided.

In client.py, make the same kind of addition to the Client __init__ method and pass along to the creation of `self._http`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by atimin** [comment]
Hey @mounte , I didn't have any better idea than to implement as you suggested. You can find the feature in the `main` branch. Thank you for your contribution!

**Comment by mounte** [comment]
Wow, nice and quick work. Will check it out tomorrow.

//
Daniel Wedlund


Den ons 14 juni 2023 kl 22:55 skrev Alexey Timin ***@***.***>:
